"""initial migration

Revision ID: 2e47aaf3d0e9
Revises: 
Create Date: 2026-02-12 10:32:42.776830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e47aaf3d0e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trees_id'), table_name='trees')
    op.drop_table('trees')
    op.drop_index(op.f('ix_yield_records_id'), table_name='yield_records')
    op.drop_table('yield_records')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_orchards_id'), table_name='orchards')
    op.drop_table('orchards')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_detections_id'), table_name='detections')
    op.drop_table('detections')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('x_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('y_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('x_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('y_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('detections_prediction_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('detections_pkey'))
    )
    op.create_index(op.f('ix_detections_id'), 'detections', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'FARMER', 'GUEST', name='userrole'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('orchard_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tree_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['orchard_id'], ['orchards.id'], name=op.f('images_orchard_id_fkey')),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name=op.f('images_tree_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('images_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('images_pkey'))
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_table('orchards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('n_trees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('orchards_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('orchards_pkey'))
    )
    op.create_index(op.f('ix_orchards_id'), 'orchards', ['id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_apples', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('good_apples', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('damaged_apples', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('healthy_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('inference_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('predictions_image_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('predictions_pkey'))
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_table('yield_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('healthy_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('damaged_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('health_index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('yield_records_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('yield_records_pkey'))
    )
    op.create_index(op.f('ix_yield_records_id'), 'yield_records', ['id'], unique=False)
    op.create_table('trees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('orchard_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tree_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tree_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['orchard_id'], ['orchards.id'], name=op.f('trees_orchard_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('trees_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trees_pkey'))
    )
    op.create_index(op.f('ix_trees_id'), 'trees', ['id'], unique=False)
    # ### end Alembic commands ###
